# -*- coding: utf-8 -*-
"""Despliegue Salario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lHfBoOxlq4p2RqOB8IJjdAFDwJ0HiRA3

# **Despliegue**


*   Cargamos el modelo

*   Cargamos los datos futuros
*   Preparar los datos futuros


*   Aplicamos el modelo para predicción
"""

#Importamos librerías básicas
#Ayudas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica

import pickle
filename= "modelo-regr.pkl"
modelo, min_max_scaler,variables= pickle.load(open(filename, 'rb'))

#Cargamos los datos futuros
#data = pd.read_csv("Nuevos_empleados_para_prediccion.csv")
#data.head()

#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title("Predicción del salario")

# Entradas numéricas
Age = st.slider('Age', min_value=18, max_value=80, value=30, step=1)
Years_of_Experience = st.slider('Years_of_Experience', min_value=0, max_value=40, value=5, step=1)

# Entradas categóricas
Gender = st.selectbox('Gender', ['Male', 'Female'])
Education_Level = st.selectbox('Education_Level', ['Bachelors', 'Masters', 'PhD', "High School"])
Job_Function = st.selectbox(
    'Job_Function',
    ['Engineering_Technology', 'Data_Analytics', 'Strategic_Sales', 'Marketing',
     'Human_Resources', 'Business_Operations', 'Project_Management', 'Other'])
Job_Rank = st.selectbox(
    'Job_Rank',
    ["Analyst", "Assistant", "Ejecutivo", "Junior", "Manager", "Senior"])

datos = [[Age, Gender, Education_Level, Years_of_Experience, Job_Function, Job_Rank]]
data = pd.DataFrame(datos, columns=['Age', 'Gender', 'Education_Level', 'Years_of_Experience', 'Job_Function', 'Job_Rank'])

#Se realiza la preparación debe ser igual al aprendizaje
data_preparada=data.copy()
data_preparada = pd.get_dummies(data_preparada, columns=['Education_Level', 'Job_Rank', 'Job_Function'], drop_first=False, dtype=int)
data_preparada = pd.get_dummies(data_preparada, columns=['Gender'], drop_first=True, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Normalizacion de variables numéricas
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()
variables_a_normalizar=['Age', 'Years_of_Experience'] #variables numéricas
min_max_scaler.fit(data_preparada[variables_a_normalizar]) #Ajuste de parámetro
data_preparada[variables_a_normalizar]= min_max_scaler.transform(data[variables_a_normalizar])
data_preparada.head()

#Hacemos la predicción con el modelo
Y_fut = modelo.predict(data_preparada)
print(Y_fut)

data['Predicción']=(Y_fut)
data.head()

"""# **Predicciones**

Calidad del modelo de Red Neuronal (NN)

Error cuadrático medio (MSE): 9.36 × 10⁷
→ Este indicador mide el promedio de los errores al cuadrado entre los valores reales y los predichos.
Un valor relativamente bajo como este sugiere que las diferencias entre los salarios reales y los estimados son pequeñas, reflejando una buena capacidad predictiva.

Raíz del error cuadrático medio (RMSE): 9,677
→ Representa el error promedio en las mismas unidades del salario.
En este caso, la Red Neuronal se equivoca, en promedio, alrededor de $9,700 dólares, lo que indica una precisión alta considerando el rango de salarios observados.

Error absoluto medio (MAE): 7,410
→ Indica que, en promedio, las predicciones del modelo difieren del salario real en aproximadamente $7,400 dólares.
Esto muestra que los errores absolutos del modelo son moderados y consistentes.

Error porcentual medio (MAPE): 0.085 (≈ 8.5%)
→ El modelo presenta un error promedio del 8.5% respecto al salario real, lo que evidencia un nivel de exactitud adecuado y un buen equilibrio entre sobreestimaciones y subestimaciones.

Error máximo (MAX): 26,595
→ El mayor error individual entre un salario real y su predicción fue de $26,595 dólares, lo que representa un caso atípico dentro del conjunto de datos, pero no afecta significativamente el desempeño general del modelo.

"""

data